### ISSUE TITLE
Compability with Pyrsistent

### ISSUE THREAD

**Issue by ShalokShalom** [tobgu/pyrthon#3]
Hi there :)

How is the compatibility with Pyrsistent?

I see that commits have been sparse over the years, but maybe is there not much to do?

How much of Pyrsistent is available in Pyrthon currently?

Much thanks!

**Comment by tobgu** [comment]
Hi!

I'm not aware of any compatibility issues for the limited scope of pyristent that pyrthon supports (pvectors, pmap and pset).

That said I think pyrthon should be viewed as a fun experiment more than anything else. I have myself not used it for anything serious. There are no plans to evolve pyrthon beyond its current state from my side. Actual bugs may be fixed if reported but as the README says the library should be viewed as experimental.
